name: Welcome, God is good! 

on: [pull_request, issues]

jobs: write

  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'perfect  day to make dreams come true'
                pr-message: 'you will win'
                

for n in range (100):
print ('te odeio')
print ('te odeio')
